<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="DSO.Core.Evoker.Json.TestApi\**" />
    <EmbeddedResource Remove="DSO.Core.Evoker.Json.TestApi\**" />
    <None Remove="DSO.Core.Evoker.Json.TestApi\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DSO.Core.Evoker\DSO.Core.Evoker.csproj" />
  </ItemGroup>

</Project>
